CREATE DATABASE DP;
USE DP;

CREATE TABLE BOLLOS_STOCK(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(20) NOT NULL,
    Inventario INT NOT NULL DEFAULT 0,
    Precio INT NOT NULL,
    Imagen VARCHAR(10) NOT NULL
);

CREATE TABLE VENTA(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Fecha TIMESTAMP NOT NULL, 
    VentaTotal INT NOT NULL,
    Artículos VARCHAR(100) NOT NULL
);

