CREATE DATABASE DP;
USE DP;

CREATE TABLE SABORES(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(20) NOT NULL,
    Precio INT NOT NULL,
    Imagen VARCHAR(10) NOT NULL
);

CREATE TABLE INVENTARIO(
    Nombre VARCHAR(20) NOT NULL,
    Precio INT NOT NULL,
    Inventario INT NOT NULL DEFAULT 0,
    FOREIGN KEY (Nombre) REFERENCES SABORES(Precio) ON UPDATE CASCADE,
    FOREIGN KEY (Precio) REFERENCES SABORES(Precio) ON UPDATE CASCADE
)

CREATE TABLE VENTA(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Fecha TIMESTAMP NOT NULL, 
    VentaTotal INT NOT NULL,
    Artículos VARCHAR(100) NOT NULL
);

CREATE TABLE USUARIOS(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Permisos VARCHAR(20) NOT NULL,
    Usuario VARCHAR(20) NOT NULL,
    Contrasena VARCHAR(12) NOT NULL
);
